main:
  - name: Situs Utama
    identifier: mainsite
    weight: 100
    params:
      header: Situs utama kareem.one.
      icon:
        vendor: font-awesome-solid
        name: globe

  - name: kareem.one
    parent: mainsite
    url: https://kareem.one
    weight: 1
    params:
      icon:
        vendor: fas
        name: globe
        className: text-primary
      description: Situs utama dari kareem.one
