# Stage 1: Hugo build
FROM node:slim AS builder

ENV HUGO_VERSION=0.138.0
ENV HUGO_CACHEDIR=/tmp/hugo_cache
ENV GO_VERSION=1.21.3

RUN apt update && apt install -y \
    curl \
    git

# Install go from downloading binary
RUN curl -L -o /tmp/go.tar.gz https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz && \
    tar -xzf /tmp/go.tar.gz -C /usr/local && \
    rm /tmp/go.tar.gz && \
    ln -s /usr/local/go/bin/go /usr/bin/go

# Install Hugo
RUN curl -L -o /tmp/hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz && \
    tar -xzf /tmp/hugo.tar.gz -C /usr/local/bin hugo && \
    chmod +x /usr/local/bin/hugo

# Install dart-sass and move the entire ./dart-sass/* into /usr/local/bin
RUN curl -L -o /tmp/dart-sass.tar.gz https://github.com/sass/dart-sass/releases/download/1.89.0/dart-sass-1.89.0-linux-x64.tar.gz && \
    tar -xzf /tmp/dart-sass.tar.gz -C /usr/local/bin --strip-components=1 && \
    rm /tmp/dart-sass.tar.gz

WORKDIR /app

# Install go deps
COPY go.mod go.sum ./
RUN go mod download

# Install hugo deps
COPY config/ config/
RUN hugo mod graph

# Install node deps
COPY package.json package-lock.json ./
RUN npm install -d

# Copy the rest of the site
COPY . .
