services:
  blog:
    image: ${BLOG_IMAGE:-git.kareem.one/shaquille/blog:latest}
    restart: unless-stopped
    networks:
      - dokploy-network
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=dokploy-network
        - traefik.http.routers.selfhosted-blog-dtrbrj-web.rule=Host(`blog.kareem.one`)
        - traefik.http.routers.selfhosted-blog-dtrbrj-web.entrypoints=web,websecure
        - traefik.http.routers.selfhosted-blog-dtrbrj-web.service=selfhosted-blog-dtrbrj-web
        - traefik.http.services.selfhosted-blog-dtrbrj-web.loadbalancer.server.port=80

networks:
  dokploy-network:
    external: true
