name: Build and Push Docker

on:
  push:
    branches: [ blog.kareem.one ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ["vm"]
    steps:
      - uses: actions/checkout@v3

      - name: Set TAG env
        id: set_tag
        run: echo "TAG=$(date +%Y%m%d%H%M)" >> "$GITHUB_ENV"

      - name: Build Docker image
        run: make docker

      - name: Push Docker image
        run: make push
