name: Build and Push Docker

on:
  push:
    branches: [ blog.kareem.one ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ["vm"]
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: make docker

      - name: Push Docker image
        run: make push
